### ISSUE TITLE
Add better log message for missing host resource in k8s authenticator

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#1296]
Relevant logs when host resource doesn't exist:
```
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="883"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418]   Sequel::Postgres::Database (3.7ms)  SELECT * FROM "resources" WHERE "resource_id" = 'my-account:webservice:conjur/authn-k8s/service'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="884"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418]   Sequel::Postgres::Database (0.4ms)  SELECT * FROM "resources" WHERE "resource_id" = 'my-account:host:conjur/authn-k8s/service/apps/.../service_account/conjur-cluster'
<13>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="885"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] Authentication Error: #<NoMethodError: undefined method `role' for nil:NilClass>
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="886"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] /opt/conjur/possum/app/domain/authentication/authn_k8s/validate_pod_request.rb:89:in `host_can_access_service?'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="887"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] /opt/conjur/possum/app/domain/authentication/authn_k8s/validate_pod_request.rb:39:in `validate_host_can_access_service'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="888"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] /opt/conjur/possum/app/domain/authentication/authn_k8s/validate_pod_request.rb:26:in `call'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="889"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] (eval):7:in `call'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="890"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] /opt/conjur/possum/app/domain/authentication/authn_k8s/inject_client_cert.rb:34:in `validate'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="891"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] /opt/conjur/possum/app/domain/authentication/authn_k8s/inject_client_cert.rb:24:in `call'
<15>1 2020-02-07T20:40:09.000+00:00 48b384beca01 conjur-possum 6390 - [meta sequenceId="892"] [origin=10.116.60.105] [request_id=897c9688-bcc5-422d-a69c-e5acc85a7b85] [tid=6418] (eval):7:in `call'
```

**Comment by orenbm** [comment]
This was fixed in this PR: https://github.com/cyberark/conjur/pull/1279
