### ISSUE TITLE
Fix SQL deprecation warning in Resource#search

### ISSUE THREAD

**Issue by kgilpin** [cyberark/conjur#141]
```
possum_1  | SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with multiple arguments or an array where the first argument/element is a string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("account(resource_id) = ?", "cucumber") to create an SQL fragment expression and pass that to the dataset filtering method, or use the auto_literal_strings extension.
possum_1  | /var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1293:in `filter_expr'
possum_1  | /var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1249:in `add_filter'
possum_1  | /var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1034:in `where'
possum_1  | /opt/possum/app/models/resource.rb:66:in `search'
possum_1  | /var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:1058:in `search'
possum_1  | /opt/possum/app/controllers/resources_controller.rb:13:in `index'
possum_1  | /var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
possum_1  | /var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
possum_1  | /var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
possum_1  | /var/lib/g
```

**Comment by izgeri** [comment]
Just noting that I also experienced this bug:

```
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with multiple arguments or an array where the first argument/element is a string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("account(resource_id) = ?", "cucumber") to create an SQL fragment expression and pass that to the dataset filtering method, or use the auto_literal_strings extension.
/var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1293:in `filter_expr'
/var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1249:in `add_filter'
/var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/dataset/query.rb:1034:in `where'
/opt/conjur-server/app/models/resource.rb:70:in `search'
/var/lib/gems/2.2.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:1058:in `search'
/opt/conjur-server/app/controllers/resources_controller.rb:14:in `index'
/var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/lib/gems/2.2.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/lib/gems/2.2.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
```

**Comment by jvanderhoof** [comment]
This has been resolved.
