### ISSUE TITLE
rake policy:load fails while loading policy

### ISSUE THREAD

**Issue by jonahx** [cyberark/conjur#1581]
## Summary
`uninitialized constant Loader::ReplacePolicy` while loading policy via conjurctl

## Steps to Reproduce
1. `cd dev`
2. `./start --authn-ldap`
3. See error

## Expected Results
Successful start
```
Creating user alice
+ docker-compose exec client conjur policy load root /src/conjur-server/dev/files/policy.yml
Loaded policy 'root'
{
  "created_roles": {
  },
  "version": 2
}
+ echo 'killing the conjur server process'
killing the conjur server process
+ docker-compose exec conjur /src/conjur-server/dev/files/killConjurServer
++ docker-compose ps -q conjur
+ docker exec -e CONJUR_AUTHN_API_KEY=34yzg2x7yhsy9tdge6d2z2kc5c3v30cr93ekeb4w249mhy13qy990d -e LDAP_URI=ldap://ldap-server:389 -e LDAP_BASE=dc=conjur,dc=net -e 'LDAP_FILTER=(uid=%s)' -e LDAP_BINDDN=cn=admin,dc=conjur,dc=net -e LDAP_BINDPW=ldapsecret -e CONJUR_AUTHENTICATORS=authn,authn-config/env,authn-ldap/test,authn-ldap/secure -it --detach-keys 'ctrl-\' c5805507d7667c15028c0c7e90d5a0c7fec47e1d567022bc25694e9405b12d93 bash
```

## Actual Results (including error logs, if applicable)
```
Setting 'admin' password
rake aborted!
NameError: uninitialized constant Loader::ReplacePolicy
/opt/conjur-server/lib/root_loader.rb:62:in `accepted_roles'
/opt/conjur-server/lib/root_loader.rb:32:in `block in load'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/opt/conjur-server/lib/root_loader.rb:17:in `load'
/opt/conjur-server/lib/tasks/policy.rake:51:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => policy:load
(See full trace by running task with --trace)
error: exit
```

**Comment by izgeri** [comment]
Note that I hit this same issue just by starting up a container with `CONJUR_ADMIN_PASSWORD` set in the container env

I'm not sure if this is the right root of my problem, but it looks like the default policy that's loaded on conjur create is modified slightly when this env var is set, and the additional policy changes that happen are also impacted by this bug.
https://github.com/cyberark/conjur/blob/f901b847da8cdc10b659d71167cba5f406b1eb77/lib/root_loader.rb#L20
