### ISSUE TITLE
[instruqt/docker] Sequel::DatabaseError: PG::InvalidFunctionDefinition

### ISSUE THREAD

**Issue by konstruktoid** [cyberark/conjur#3009]
## Summary

When trying to complete [Secure Ansible SSH Keys and Secrets in Ansible Playbooks](https://www.conjur.org/get-started/interactive/secure-ansible-automation/) the "Install Conjur" step fails.

## Steps to Reproduce

1. Visit [Secure Ansible SSH Keys and Secrets in Ansible Playbooks](https://www.conjur.org/get-started/interactive/secure-ansible-automation/)
2. Complete the steps and try to complete the "Install Conjur" step
3. The `docker-compose exec conjur conjurctl account create demo | tee conjur/admin.out` command will not return anything
4. Run `docker ps -a`
5. The `cyberark/conjur "conjurctl server" ` container has exited.

## Expected Results

The `cyberark/conjur "conjurctl server" ` container should be up and running.

## Actual Results

```sh
~# docker logs root_conjur_1
....rake aborted!
Sequel::DatabaseError: PG::InvalidFunctionDefinition: ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:532:in `_execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `execute'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:17:in `block (3 levels) in <top (required)>'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `each'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `instance_exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `apply'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:695:in `block (2 levels) in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:195:in `transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:482:in `checked_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:694:in `block in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `each'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:409:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/migrations.rb:12:in `migrate'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/railties/database.rake:172:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
PG::InvalidFunctionDefinition: ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:532:in `_execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `execute'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:17:in `block (3 levels) in <top (required)>'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `each'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `instance_exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `apply'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:695:in `block (2 levels) in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:195:in `transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:482:in `checked_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:694:in `block in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `each'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:409:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/migrations.rb:12:in `migrate'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/railties/database.rake:172:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
error: exit
rake aborted!
Sequel::DatabaseError: PG::InvalidFunctionDefinition: ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:532:in `_execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `execute'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:17:in `block (3 levels) in <top (required)>'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `each'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `instance_exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `apply'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:695:in `block (2 levels) in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:195:in `transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:482:in `checked_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:694:in `block in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `each'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:409:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/migrations.rb:12:in `migrate'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/railties/database.rake:172:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
PG::InvalidFunctionDefinition: ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:159:in `execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:532:in `_execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/adapters/postgres.rb:348:in `execute'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:17:in `block (3 levels) in <top (required)>'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `each'
/opt/conjur-server/db/migrate/202402230827123_policy_log_trigger_up.rb:14:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `instance_exec'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:110:in `apply'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:695:in `block (2 levels) in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:258:in `_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/connecting.rb:293:in `synchronize'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/database/transactions.rb:195:in `transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:482:in `checked_transaction'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:694:in `block in run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `each'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:691:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-5.69.0/lib/sequel/extensions/migration.rb:409:in `run'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/migrations.rb:12:in `migrate'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/sequel-rails-1.2.0/lib/sequel_rails/railties/database.rake:172:in `block (2 levels) in <top (required)>'
/opt/conjur-server/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
error: exit
```

## Reproducible

   * [X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number

```sh
~# docker images
REPOSITORY            TAG       IMAGE ID       CREATED        SIZE
cyberark/conjur       latest    f077bb3cb91b   7 weeks ago    358MB
cyberark/conjur-cli   8         3c83ef7e3df8   3 months ago   127MB
postgres              9.6       027ccf656dc1   2 years ago    200MB
postgres              9.3       c230b2f564da   5 years ago    223MB
~# cat docker-compose.yml 
version: '3'
services:
  database:
    image: postgres:9.3

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]
    ports:
      - "8080:80"

  client:
    image: cyberark/conjur-cli:8
    depends_on: [ conjur ]
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_API_KEY:
      CONJUR_AUTHN_LOGIN: admin
```

## Environment setup

Whatever Instruqt uses for [Secure Ansible SSH Keys and Secrets in Ansible Playbooks](https://www.conjur.org/get-started/interactive/secure-ansible-automation/)

**Comment by konstruktoid** [comment]
```sh
~# docker logs root_database_1
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
creating configuration files ... ok
creating template1 database in /var/lib/postgresql/data/base/1 ... ok
initializing pg_authid ... ok
setting password ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D /var/lib/postgresql/data
or
    pg_ctl -D /var/lib/postgresql/data -l logfile start

****************************************************
WARNING: No password has been set for the database.
         This will allow anyone with access to the
         Postgres port to access your database. In
         Docker's default configuration, this is
         effectively any other container on the same
         system.

         Use "-e POSTGRES_PASSWORD=password" to set
         it in "docker run".
****************************************************
waiting for server to start....LOG:  database system was shut down at 2024-11-11 14:02:15 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
LOG:  shutting down
waiting for server to shut down....LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  database system was shut down at 2024-11-11 14:02:17 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  relation "schema_migrations" does not exist at character 27
STATEMENT:  SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
ERROR:  relation "schema_info" does not exist at character 27
STATEMENT:  SELECT NULL AS "nil" FROM "schema_info" LIMIT 1
ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
STATEMENT:          CREATE OR REPLACE FUNCTION current_policy_version_no_policy_text()
                RETURNS SETOF policy_versions
                SET search_path FROM CURRENT
                LANGUAGE sql STABLE AS $$
                  SELECT resource_id, role_id, "version", created_at, NULL as policy_text, policy_sha256, finished_at, client_ip 
                  FROM policy_versions WHERE finished_at IS NULL
                $$;

LOG:  received smart shutdown request
LOG:  autovacuum launcher shutting down
LOG:  shutting down
LOG:  database system is shut down
LOG:  database system was shut down at 2024-11-11 14:12:12 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  return type mismatch in function declared to return policy_versions
DETAIL:  Final statement returns unknown instead of text at column 5.
CONTEXT:  SQL function "current_policy_version_no_policy_text"
STATEMENT:          CREATE OR REPLACE FUNCTION current_policy_version_no_policy_text()
                RETURNS SETOF policy_versions
                SET search_path FROM CURRENT
                LANGUAGE sql STABLE AS $$
                  SELECT resource_id, role_id, "version", created_at, NULL as policy_text, policy_sha256, finished_at, client_ip 
                  FROM policy_versions WHERE finished_at IS NULL
                $$;

```
